name: "OpenWRT Builder"
slug: "openwrt_builder"
description: "OpenWRT ImageBuilder backend for Home Assistant"
version: "0.9.6"
startup: services
boot: auto
arch:
  - amd64
  - aarch64
  - armv7
  - armhf
init: false
ingress: true
ingress_port: 8080
panel_icon: mdi:router-wireless
options: {}
schema: {}
map: ["data:rw"]
tempfs: true
ports:
  8080/tcp: 8080
watchdog: http://[HOST]:8080/api/v1/health
